### ISSUE TITLE
Export separate type declarations for each supported language

### ISSUE THREAD

**Issue by jaydenseric** [Sec-ant/prettier-plugin-embed#52]
Firstly thanks for the work on this project; it's my first day trying it and this could be a game changer! We have a lot of SQL template strings in TypeScript modules and manually formatting it all is a big hassle.

With this TypeScript config `compilerOptions`:

```json
{
  "allowJs": true,
  "forceConsistentCasingInFileNames": true,
  "verbatimModuleSyntax": true,
  "maxNodeModuleJsDepth": 10,
  "module": "nodenext",
  "noEmit": true,
  "strict": true,
  "target": "es2022"
}
```

And with this `prettier.config.mjs`:

```js
// @ts-check

/**
 * Prettier config for the plugin `prettier-plugin-embed`.
 * @type {import("prettier-plugin-embed").PrettierPluginEmbedOptions}
 */
const prettierConfigPluginEmbed = {
  embeddedSqlIdentifiers: ["sql", "tricentisVisualTestingSql"],
};

/**
 * Prettier config for the plugin `prettier-plugin-sql`.
 * @type {import("prettier-plugin-sql").SqlBaseOptions}
 */
const prettierConfigPluginSql = {
  language: "postgresql",
};

/**
 * Prettier config.
 * @type {import("prettier").Config}
 */
const prettierConfig = {
  plugins: ["prettier-plugin-embed", "prettier-plugin-sql"],
  ...prettierConfigPluginEmbed,
  ...prettierConfigPluginSql,
};

export default prettierConfig;
```

And with the dev dependencies `prettier-plugin-embed` and `prettier-plugin-sql` installed, running a TypeScript type check on the project results in these 3 TypeScript errors:

```
node_modules/prettier-plugin-embed/dist/embedded/sql/options.d.ts:34:31 - error TS2312: An interface can only extend an object type or intersection of object types with statically known members.

34     interface Options extends PrettierPluginDepsOptions {
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/prettier-plugin-embed/dist/embedded/xml/parser.d.ts:1:30 - error TS2307: Cannot find module 'chevrotain' or its corresponding type declarations.

1 import type { CstNode } from "chevrotain";
                               ~~~~~~~~~~~~

node_modules/prettier-plugin-sql/shim.d.ts:4:3 - error TS1203: Export assignment cannot be used when targeting ECMAScript modules. Consider using 'export default' or another module format instead.

4   export = JSOX
    ~~~~~~~~~~~~~


Found 3 errors in 3 files.

Errors  Files
     1  node_modules/prettier-plugin-embed/dist/embedded/sql/options.d.ts:34
     1  node_modules/prettier-plugin-embed/dist/embedded/xml/parser.d.ts:1
     1  node_modules/prettier-plugin-sql/shim.d.ts:4
```

The first seems to be a TypeScript error about how interfaces and object types are composed, which is surprising because surely if they are incorrect the `prettier-plugin-embed` compilation tooling would have reported it? Maybe the types are manually authored but not type checked by TypeScript? I haven't looked into it.

The second one looks like it might be a tricky error relating to optional peer dependencies or something, since I'm not using xml formatting yet in this project? Ideally runtime code as well as types would not get pulled into your project if they are not being used by your project.

The one relating to the shim definitions looks like a legit bug to be fixed in the way the `prettier-plugin-sql` types are generated, regarding module format.

**Comment by Sec-ant** [comment]
I suggest set [`skipLibCheck`](https://www.typescriptlang.org/tsconfig#skipLibCheck) to `true` in your tsconfig.

**Comment by Sec-ant** [comment]
@jaydenseric Have you tried setting `skipLibCheck` to `true` and does it solve your issue?

**Comment by Sec-ant** [comment]
Close due to lack of response

**Comment by jaydenseric** [comment]
Respectfully, this issue is raised in this repo because there are objectively TypeScript errors in the published types. It shouldn't be closed on the basis of whether or not at my work we choose to ignore those errors in our project or not.

**Comment by Sec-ant** [comment]
Thank you for your report. I closed it because I didn't receive further responses.

- The first type error occurs because this plugin was developed using a lower version of the `prettier-plugin-sql` at that time. And when it is used with a newer version of `prettier-plugin-sql` which changes one of its exported types, it breaks the type declarations. This was fixed in v0.4.0.

- The second type error occurs because this plugin supports many languages by leveraging the language plugins. And many of the plugins don't behave in the same manner, nor have a unified style to provide types. So inside this plugin we will have to do some manual tweaks and even hacks for them to work. Also this plugin registers the language-specific option types of the language plugins into the prettier global `Options` type for convenient type hints and autocompletes. Therefore, some of the language plugins types are included inside this plugin. However a user will most probably only install and use only one of the language plugins, so type declarations from other language plugins cannot be found and therefore errors occur. As types are statically resolved, I'm not sure there will be a **solution** other than using `skipLibCheck`.

- The third type error is not generated from this plugin.

So although ignoring those errors doesn't seem the correct way to solve them, I still suggest setting `skipLibCheck` to `true`, which can save you a great amount of time resolving the types, while without breaking any functions brought by this package.

**Comment by jaydenseric** [comment]
Thanks for reopening 🙏

It's incorrect for types to assume what optional dependencies you have installed, and that intellisense might make a user think they can use options in their config that are actually unavailable for their kind of setup.

The right way to handle this, is to publish seperate modules containing types for each of the optional language plugins, and users can deep import the right types to use for their project.

Maybe export a module with the types for options common to every setup, then have seperate deep importable modules with exporting types for each language and a user can import them all and combine them in their project config.

**Comment by Sec-ant** [comment]
> It's incorrect for types to assume what optional dependencies you have installed, and that intellisense might make a user think they can use options in their config that are actually unavailable for their kind of setup.

Very fair point. I love this approach too. I'll see if I can export separate type declaration files for each of the supported languages.

**Comment by Sec-ant** [comment]
Well, I find this difficult after a second thought.

Here are the 2 things we know:

- Prettier requires the plugin to export an `options` object so that it can pick up the options that are supported by the plugin.
- There is only one way to load a plugin, which is to put the plugin into the `plugins` list in the config file of Prettier.

So if I want to support a language, I'll have to register at least one additional option: `embedded<Language>Identifiers` into the big `options` object of `prettier-plugin-embed`, no matter whether plugin users will use it or not. Because there's no other way to conditionally load a "sub-plugin" in Prettier. Unless I make one plugin for each language.

To be clear, this isn't only about `options`, what I want to say is that the runtime code to support a language cannot be conditionally included. It will have to be included in the bundle. Therefore some language-specific types can also inevitably appear in the output, even if the user isn't plan to use that language.

IMHO, a proper solution is that Prettier should add a new API for each language-specific plugin to configure how the language should be formatted when it is embedded in another language (for this plugin, the "another language" is js/ts). And at the same time, it should also add an API for language plugins to define what is considered "embedded" in their language.

**Comment by Sec-ant** [comment]
I think this issue will be fixed by this #68, could you try out the [codesandbox-ci](https://github.com/Sec-ant/prettier-plugin-embed/pull/68#issuecomment-1905571800) package to check? @jaydenseric

Also, there's a small breaking change in #68, I renamed `PrettierPluginEmbedOptions` to `PluginEmbedOptions`. And just like what you suggested [here](https://github.com/Sec-ant/prettier-plugin-embed/issues/52#issuecomment-1880580355), the language specific types are exported to the users for them to manually include in the following two ways:

- Augment the `Options` type from `Prettier` to use plugin-specific options.
  ```ts
  /// <reference types="prettier-plugin-embed/plugin-embed" />
  /// <reference types="prettier-plugin-embed/embedded/sql/plugin-sql" />
  ```

- Import plugin-specific options.
  ```ts
  import type { PluginEmbedOptions } from "prettier-plugin-embed";
  import type { PluginSqlOptions } from "prettier-plugin-embed/embedded/sql/plugin-sql-types";
  // You can also import the types from the `prettier-plugin-sql` plugin directly,
  // but not all plugins provide types, or provide them in a predictable way,
  // so I also export them in this plugin.
  ```

**Comment by jaydenseric** [comment]
@Sec-ant exciting progress! I tried the following:

```
npm i https://pkg.csb.dev/Sec-ant/prettier-plugin-embed/commit/cbe880cf/prettier-plugin-embed --save-dev
```

Then with this `prettier.config.mjs`:

```js
// @ts-check

/**
 * Prettier config for the plugin `prettier-plugin-embed`.
 * @satisfies {import("prettier-plugin-embed").PluginEmbedOptions}
 */
const prettierConfigPluginEmbed = {
  embeddedSqlIdentifiers: ["SQL", "sql", "tricentisVisualTestingSql"],
};

/**
 * Prettier config for the plugin `prettier-plugin-sql`.
 * @satisfies {import("prettier-plugin-embed/embedded/sql/plugin-sql-types").PluginSqlOptions}
 */
const prettierConfigPluginSql = {
  language: "postgresql",
  keywordCase: "upper",
};

/**
 * Prettier config.
 * @satisfies {import("prettier").Config}
 */
const prettierConfig = {
  plugins: ["prettier-plugin-embed", "prettier-plugin-sql"],
  ...prettierConfigPluginEmbed,
  ...prettierConfigPluginSql,
};

export default prettierConfig;
```

But this results in the following TypeScript error about the SQL plugin option `language`:

```
Object literal may only specify known properties, and 'language' does not exist in type 'Partial<OmitIndexSignature<NormalizedSqlBaseOptions>>'. ts(2353)
```

<img width="1116" alt="Screenshot 2024-01-24 at 9 22 09 AM" src="https://github.com/Sec-ant/prettier-plugin-embed/assets/1754873/4b3ff396-5dc5-40b7-ba55-74a1e6adb204">

**Comment by Sec-ant** [comment]
Thanks for catching that. I [pushed a fix](https://github.com/Sec-ant/prettier-plugin-embed/pull/68/commits/49175be4463074d2a147b24357d77204203fced9), would you please try again?

**Comment by jaydenseric** [comment]
Now I get:

```
node_modules/prettier-plugin-sql/shim.d.ts:4:3 - error TS1203: Export assignment cannot be used when targeting ECMAScript modules. Consider using 'export default' or another module format instead.

4   export = JSOX
    ~~~~~~~~~~~~~


Found 1 error in node_modules/prettier-plugin-sql/shim.d.ts:4
```

**Comment by jaydenseric** [comment]
Before I was only testing with the VS Code GUI, but now I tested using the `tsc` CLI. The CLI approach is the most correct for reporting errors; sometimes VS Code fails to surface errors correctly in the UI.

**Comment by Sec-ant** [comment]
Yeah, but as you can see the `export = JSOX` issue is from `prettier-plugin-sql`, I don't think this is a issue that I can fix?

**Comment by Sec-ant** [comment]
Again thanks for raising this issue, it helps me reevaluate the structure of the codebase and keep it more maintainable. I'm now going to merge #68 and close this, as the type check error here is not from this package. If this really bothers you, I'd suggest asking for a fix in the corresponding repo.
